- id: '1742337005391'
  alias: Office Switch
  description: ''
  use_blueprint:
    path: light_switch.yaml
    input:
      light: light.office
      switch: switch.office
- id: '1742259737852'
  alias: Office Switch Button 1
  description: ''
  use_blueprint:
    path: scene_controller_button.yaml
    input:
      button: event.office_switch_button_1
      actions:
      - action: script.office_bright
        metadata: {}
        data: {}
- id: '1742259802006'
  alias: Office Switch Button 2
  description: ''
  use_blueprint:
    path: scene_controller_button.yaml
    input:
      button: event.office_switch_button_2
      actions:
      - action: script.office_nightlight
        metadata: {}
        data: {}
- id: '1742259852048'
  alias: Office Switch Button 3
  description: ''
  use_blueprint:
    path: scene_controller_button.yaml
    input:
      button: event.office_switch_button_3
      actions:
      - action: script.office_work
        metadata: {}
        data: {}
- id: '1742337280749'
  alias: Bedroom Switch
  description: ''
  use_blueprint:
    path: light_switch.yaml
    input:
      light: light.bedroom
      switch: switch.bedroom
- id: '1742265800631'
  alias: Bedroom Switch Button 1
  description: ''
  use_blueprint:
    path: scene_controller_button.yaml
    input:
      button: event.bedroom_switch_button_1
      actions:
      - action: script.bedroom_bright
        metadata: {}
        data: {}
- id: '1742265845066'
  alias: Bedroom Switch Button 2
  description: ''
  use_blueprint:
    path: scene_controller_button.yaml
    input:
      button: event.bedroom_switch_button_2
      actions:
      - action: script.bedroom_reading
        metadata: {}
        data: {}
- id: '1742265919265'
  alias: Bedroom Switch Button 3
  description: ''
  use_blueprint:
    path: scene_controller_button.yaml
    input:
      button: event.bedroom_switch_button_3
      actions:
      - action: script.bedroom_play
        metadata: {}
        data: {}
- id: '1742337248521'
  alias: Loft Switch
  description: ''
  use_blueprint:
    path: light_switch.yaml
    input:
      light: light.loft_wall
      switch: switch.loft
- id: '1742268121309'
  alias: Loft Switch Button 1
  description: ''
  use_blueprint:
    path: scene_controller_button.yaml
    input:
      button: event.loft_switch_button_1
      actions:
      - action: script.loft_bright
        metadata: {}
        data: {}
- id: '1742273165518'
  alias: Loft Switch Button 2
  description: ''
  use_blueprint:
    path: scene_controller_button.yaml
    input:
      button: event.loft_switch_button_2
      actions:
      - action: script.loft_christmas
        metadata: {}
        data: {}
- id: '1742273188065'
  alias: Loft Switch Button 3
  description: ''
  use_blueprint:
    path: scene_controller_button.yaml
    input:
      button: event.loft_switch_button_3
      actions:
      - action: script.loft_play
        metadata: {}
        data: {}
- id: '1742337322652'
  alias: Dining Room Switch
  description: ''
  use_blueprint:
    path: light_switch.yaml
    input:
      light: light.dining_room
      switch: switch.dining_room
- id: '1744102789672'
  alias: Dining Room Switch Button 1
  description: ''
  use_blueprint:
    path: scene_controller_button.yaml
    input:
      button: event.dining_room_switch_button_1
      actions:
      - action: light.toggle
        metadata: {}
        data:
          brightness_pct: 100
        target:
          entity_id:
          - light.dining_room_chandelier
          - light.dining_room_spots
- id: '1745017281980'
  alias: Bedroom Pico Raise
  description: ''
  use_blueprint:
    path: pico_remote_button.yaml
    input:
      device: b0881bdabe428061b6e34aa09b9386d6
      button: raise
      press:
      - action: scene.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: scene.bedroom_nighttime
      long_press:
      - action: scene.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: scene.bedroom_open
- id: '1745017343700'
  alias: Bedroom Pico Lower
  description: ''
  use_blueprint:
    path: pico_remote_button.yaml
    input:
      device: b0881bdabe428061b6e34aa09b9386d6
      button: lower
      press:
      - action: scene.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: scene.bedroom_daytime
- id: '1752608870374'
  alias: Office Pico Raise
  description: ''
  use_blueprint:
    path: pico_remote_button.yaml
    input:
      device: beb7140be21d2a179f64ec52b946edca
      button: raise
      press:
      - action: scene.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: scene.office_nighttime
      long_press:
      - action: scene.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: scene.office_open
- id: '1752608748598'
  alias: Office Pico Lower
  description: ''
  use_blueprint:
    path: pico_remote_button.yaml
    input:
      device: beb7140be21d2a179f64ec52b946edca
      button: lower
      press:
      - action: scene.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: scene.office_daytime
- id: '1745249879161'
  alias: Dining Room Switch Button 3
  description: ''
  use_blueprint:
    path: scene_controller_button.yaml
    input:
      button: event.dining_room_switch_button_3
      actions:
      - action: script.dining_room_play
        metadata: {}
        data: {}
- id: '1750177081187'
  alias: Dining Room Switch Button 2
  description: ''
  use_blueprint:
    path: scene_controller_button.yaml
    input:
      button: event.dining_room_switch_button_2
      actions:
      - action: script.dining_room_dnd
        metadata: {}
        data: {}
- id: '1752632839285'
  alias: Bedroom Pico On
  description: ''
  use_blueprint:
    path: pico_remote_button.yaml
    input:
      device: b0881bdabe428061b6e34aa09b9386d6
      button: 'on'
      press:
      - action: scene.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: scene.bedroom_blackout_open
- id: '1752632870011'
  alias: Bedroom Pico Off
  description: ''
  use_blueprint:
    path: pico_remote_button.yaml
    input:
      device: b0881bdabe428061b6e34aa09b9386d6
      button: 'off'
      press:
      - action: scene.turn_on
        metadata: {}
        data: {}
        target:
          entity_id: scene.bedroom_blackout_close
- id: '1758341059232'
  alias: Office Lights
  description: ''
  use_blueprint:
    path: occupancy_lights.yaml
    input:
      lights:
      - light.office
      occupancy: binary_sensor.office_aziz
- id: '1758341121396'
  alias: Bedroom Lights
  description: ''
  use_blueprint:
    path: occupancy_lights.yaml
    input:
      lights:
      - light.bedroom
      occupancy: binary_sensor.bedroom_aziz
- id: '1758341153495'
  alias: Loft Lights
  description: ''
  use_blueprint:
    path: occupancy_lights.yaml
    input:
      lights:
      - light.loft_wall
      occupancy: binary_sensor.loft_aziz
- id: '1758341469250'
  alias: Dining Room Lights
  description: ''
  use_blueprint:
    path: occupancy_lights.yaml
    input:
      lights:
      - light.dining_room
      - light.dining_room_lego
      occupancy: binary_sensor.dining_room_aziz
- id: '1758395540557'
  alias: Bedroom Blinds
  description: ''
  use_blueprint:
    path: night_blinds.yaml
    input:
      daytime: scene.bedroom_daytime
      nighttime: scene.bedroom_nighttime
      window: binary_sensor.bedroom_window
      privacy: input_boolean.bedroom_privacy
- id: '1758395564309'
  alias: Office Blinds
  description: ''
  use_blueprint:
    path: night_blinds.yaml
    input:
      daytime: scene.office_daytime
      nighttime: scene.office_nighttime
      window: binary_sensor.office_window
      privacy: input_boolean.office_privacy
- id: '1765411645826'
  alias: Christmas Lights
  description: ''
  use_blueprint:
    path: occupancy_lights.yaml
    input:
      lights:
      - light.balcony_icicles
      - light.beam_icicles
      - light.tree_lights
      occupancy: binary_sensor.home_active
