# Loads default set of integrations. Do not remove.
default_config:

http:
  ssl_certificate: /config/homeassistant-cert.pem
  ssl_key: /config/homeassistant-key.pem

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Load UI from YAML.
lovelace:
  mode: storage
  dashboards:
    lovelace-home:
      mode: yaml
      title: Home
      icon: mdi:home
      show_in_sidebar: true
      filename: ui-lovelace-home.yaml

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

automation yaml: !include_dir_list automations/
script yaml: !include_dir_named scripts/
template: !include_dir_merge_list templates/

media_player: !include_dir_list media_players/

# Enable earthquake entities
geo_location:
  - platform: usgs_earthquakes_feed
    feed_type: "past_day_all_earthquakes"
